name: organization

on: push

jobs:
  organization-member:
    runs-on: ubuntu-latest
    steps:
      - name: run curl
        id: get_check_code
        run: |
          http_code=`curl -s --head -I -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members/fish0607 | awk '/HTTP/{print $2}'`
          echo "${http_code}"
          echo "======"
          http_code=`curl -s --head -I -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members/fish9167 | awk '/HTTP/{print $2}'`
          echo "${http_code}"
          echo "======"
          echo "::set-output name=http_code::${http_code}"
          
      - name: echo staus
        run: |
          echo "${{ steps.get_check_code.outputs.http_code }}"    
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.SERVICE }}
          issue-number: 1
          body: |
            Please check the result of `run test cases`:
            - Test Platform: macOS
            - Editor Version: 3
            - Task Result:3
            - Task URL: 33333
            - GitHub Action: https://github.com/cocos/cocos-engine/actions/runs/33333
            ## Task Details
            fdsafdsafdsa
#       - name: Create comment
#         uses: peter-evans/create-or-update-comment@v2
#         with:
#           issue-number: 1
#           body: |
#             Please check the redddsult of `run test cases`:

